### ISSUE TITLE
Work with Professor Conrad to understand how to use JSON, MLab, and Java altogether 

### ISSUE THREAD

**Issue by dianephan** [ucsb-cs56-f18/ucsb-cs56-where-is-every1#15]

**Comment by dianephan** [comment]
worked with Professor Conrad on Monday after class. he helped us get json files for our project

**Comment by lleeoochen** [comment]
Mentor Approved: 100 points

**Comment by dianephan** [comment]
after class on Monday 11/26, Juan, Andrew, and I stayed after class to work with Professor Conrad on this tutorial to retrieve json files: 
https://github.com/ucsb-cs56-pconrad/simple-json-jackson-demo

**Comment by lleeoochen** [comment]
JSON file: https://github.com/ucsb-cs56-pconrad/simple-json-jackson-demo/blob/master/src/main/resources/buildings.json
