### ISSUE TITLE
Provide documentation for the whole project 

### ISSUE THREAD

**Issue by dianephan** [ucsb-cs56-f18/ucsb-cs56-where-is-every1#17]

**Comment by lleeoochen** [comment]
Mentor Approved: 150 points

**Comment by dianephan** [comment]
Documentation can be found here: https://ucsb-cs56-f18.github.io/ucsb-cs56-where-is-every1/apidocs/ 

More info about our project here: https://github.com/ucsb-cs56-f18/ucsb-cs56-where-is-every1/wiki
