### ISSUE TITLE
Learn and implement all user interfaces using Thymeleaf Templating

### ISSUE THREAD

**Issue by agprice** [ucsb-cs56-f18/ucsb-cs56-where-is-every1#8]
Freemarker is harder to do incremental design with, and doesn't work as well for our project, so instead all dynamic webpages will be implemented using the Thymeleaf templating engine. Thymeleaf allows HTML that can be correctly displayed in browsers and also work as static prototypes, allowing for stronger collaboration in development teams. The goal of this issue is to learn and move the project from Freemarker to Thymeleaf.

**Comment by lleeoochen** [comment]
Mentor Approved: 100 points.

100 points are for learning a different framework, and the points for UI implementations (basics) on this framework will go to issue #5. Let me know if you think this issue needs more points. Thanks.
